// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'system_env_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$SystemEnvResponseImpl _$$SystemEnvResponseImplFromJson(
  Map<String, dynamic> json,
) => _$SystemEnvResponseImpl(
  success: json['success'] as bool,
  message: json['message'] as String?,
  data: json['data'] == null
      ? null
      : SystemEnvData.fromJson(json['data'] as Map<String, dynamic>),
);

_$SystemEnvDataImpl _$$SystemEnvDataImplFromJson(
  Map<String, dynamic> json,
) => _$SystemEnvDataImpl(
  configDir: json['CONFIG_DIR'] as String?,
  debug: _boolFromJson(json['DEBUG']),
  logLevel: json['LOG_LEVEL'] as String?,
  logMaxFileSize: _intFromJson(json['LOG_MAX_FILE_SIZE']),
  logBackupCount: _intFromJson(json['LOG_BACKUP_COUNT']),
  logConsoleFormat: json['LOG_CONSOLE_FORMAT'] as String?,
  logFileFormat: json['LOG_FILE_FORMAT'] as String?,
  asyncFileQueueSize: _intFromJson(json['ASYNC_FILE_QUEUE_SIZE']),
  asyncFileWorkers: _intFromJson(json['ASYNC_FILE_WORKERS']),
  batchWriteSize: _intFromJson(json['BATCH_WRITE_SIZE']),
  writeTimeout: _doubleFromJson(json['WRITE_TIMEOUT']),
  projectName: json['PROJECT_NAME'] as String?,
  appDomain: json['APP_DOMAIN'] as String?,
  apiV1Str: json['API_V1_STR'] as String?,
  frontendPath: json['FRONTEND_PATH'] as String?,
  tz: json['TZ'] as String?,
  host: json['HOST'] as String?,
  port: _intFromJson(json['PORT']),
  nginxPort: _intFromJson(json['NGINX_PORT']),
  dev: _boolFromJson(json['DEV']),
  advancedMode: _boolFromJson(json['ADVANCED_MODE']),
  allowedHosts: _stringListFromJson(json['ALLOWED_HOSTS']),
  accessTokenExpireMinutes: _intFromJson(json['ACCESS_TOKEN_EXPIRE_MINUTES']),
  resourceAccessTokenExpireSeconds: _intFromJson(
    json['RESOURCE_ACCESS_TOKEN_EXPIRE_SECONDS'],
  ),
  superuser: json['SUPERUSER'] as String?,
  superuserPassword: json['SUPERUSER_PASSWORD'] as String?,
  auxiliaryAuthEnable: _boolFromJson(json['AUXILIARY_AUTH_ENABLE']),
  apiToken: json['API_TOKEN'] as String?,
  authSite: json['AUTH_SITE'] as String?,
  dbType: json['DB_TYPE'] as String?,
  dbEcho: _boolFromJson(json['DB_ECHO']),
  dbTimeout: _intFromJson(json['DB_TIMEOUT']),
  dbWalEnable: _boolFromJson(json['DB_WAL_ENABLE']),
  dbPoolType: json['DB_POOL_TYPE'] as String?,
  dbPoolPrePing: _boolFromJson(json['DB_POOL_PRE_PING']),
  dbPoolRecycle: _intFromJson(json['DB_POOL_RECYCLE']),
  dbPoolTimeout: _intFromJson(json['DB_POOL_TIMEOUT']),
  dbSqlitePoolSize: _intFromJson(json['DB_SQLITE_POOL_SIZE']),
  dbSqliteMaxOverflow: _intFromJson(json['DB_SQLITE_MAX_OVERFLOW']),
  dbPostgresqlHost: json['DB_POSTGRESQL_HOST'] as String?,
  dbPostgresqlPort: _intFromJson(json['DB_POSTGRESQL_PORT']),
  dbPostgresqlDatabase: json['DB_POSTGRESQL_DATABASE'] as String?,
  dbPostgresqlUsername: json['DB_POSTGRESQL_USERNAME'] as String?,
  dbPostgresqlPassword: json['DB_POSTGRESQL_PASSWORD'] as String?,
  dbPostgresqlPoolSize: _intFromJson(json['DB_POSTGRESQL_POOL_SIZE']),
  dbPostgresqlMaxOverflow: _intFromJson(json['DB_POSTGRESQL_MAX_OVERFLOW']),
  cacheBackendType: json['CACHE_BACKEND_TYPE'] as String?,
  cacheBackendUrl: json['CACHE_BACKEND_URL'] as String?,
  cacheRedisMaxmemory: _intFromJson(json['CACHE_REDIS_MAXMEMORY']),
  globalImageCache: _boolFromJson(json['GLOBAL_IMAGE_CACHE']),
  globalImageCacheDays: _intFromJson(json['GLOBAL_IMAGE_CACHE_DAYS']),
  tempFileDays: _intFromJson(json['TEMP_FILE_DAYS']),
  metaCacheExpire: _intFromJson(json['META_CACHE_EXPIRE']),
  proxyHost: json['PROXY_HOST'] as String?,
  dohEnable: _boolFromJson(json['DOH_ENABLE']),
  dohDomains: json['DOH_DOMAINS'] as String?,
  dohResolvers: json['DOH_RESOLVERS'] as String?,
  searchSource: json['SEARCH_SOURCE'] as String?,
  recognizeSource: json['RECOGNIZE_SOURCE'] as String?,
  scrapSource: json['SCRAP_SOURCE'] as String?,
  animeGenreIds: _intListFromJson(json['ANIME_GENREIDS']),
  tmdbImageDomain: json['TMDB_IMAGE_DOMAIN'] as String?,
  tmdbApiDomain: json['TMDB_API_DOMAIN'] as String?,
  tmdbLocale: json['TMDB_LOCALE'] as String?,
  tmdbScrapOriginalImage: _boolFromJson(json['TMDB_SCRAP_ORIGINAL_IMAGE']),
  tmdbApiKey: json['TMDB_API_KEY'] as String?,
  tvdbV4ApiKey: json['TVDB_V4_API_KEY'] as String?,
  tvdbV4ApiPin: json['TVDB_V4_API_PIN'] as String?,
  fanartEnable: _boolFromJson(json['FANART_ENABLE']),
  fanartLang: json['FANART_LANG'] as String?,
  fanartApiKey: json['FANART_API_KEY'] as String?,
  u115AppId: json['U115_APP_ID'] as String?,
  u115AuthServer: json['U115_AUTH_SERVER'] as String?,
  alipanAppId: json['ALIPAN_APP_ID'] as String?,
  moviepilotAutoUpdate: json['MOVIEPILOT_AUTO_UPDATE'] as String?,
  autoUpdateResource: _boolFromJson(json['AUTO_UPDATE_RESOURCE']),
  rmtMediaext: _stringListFromJson(json['RMT_MEDIAEXT']),
  rmtSubext: _stringListFromJson(json['RMT_SUBEXT']),
  rmtAudioext: _stringListFromJson(json['RMT_AUDIOEXT']),
  mediaserverSyncInterval: _intFromJson(json['MEDIASERVER_SYNC_INTERVAL']),
  subscribeMode: json['SUBSCRIBE_MODE'] as String?,
  subscribeRssInterval: _intFromJson(json['SUBSCRIBE_RSS_INTERVAL']),
  subscribeStatisticShare: _boolFromJson(json['SUBSCRIBE_STATISTIC_SHARE']),
  subscribeSearch: _boolFromJson(json['SUBSCRIBE_SEARCH']),
  subscribeSearchInterval: _intFromJson(json['SUBSCRIBE_SEARCH_INTERVAL']),
  localExistsSearch: _boolFromJson(json['LOCAL_EXISTS_SEARCH']),
  sitedataRefreshInterval: _intFromJson(json['SITEDATA_REFRESH_INTERVAL']),
  siteMessage: _boolFromJson(json['SITE_MESSAGE']),
  noCacheSiteKey: json['NO_CACHE_SITE_KEY'] as String?,
  ocrHost: json['OCR_HOST'] as String?,
  browserEmulation: json['BROWSER_EMULATION'] as String?,
  flaresolverrUrl: json['FLARESOLVERR_URL'] as String?,
  searchMultipleName: _boolFromJson(json['SEARCH_MULTIPLE_NAME']),
  maxSearchNameLimit: _intFromJson(json['MAX_SEARCH_NAME_LIMIT']),
  torrentTag: json['TORRENT_TAG'] as String?,
  downloadSubtitle: _boolFromJson(json['DOWNLOAD_SUBTITLE']),
  autoDownloadUser: json['AUTO_DOWNLOAD_USER'] as String?,
  downloadTmpext: _stringListFromJson(json['DOWNLOAD_TMPEXT']),
  cookiecloudEnableLocal: _boolFromJson(json['COOKIECLOUD_ENABLE_LOCAL']),
  cookiecloudHost: json['COOKIECLOUD_HOST'] as String?,
  cookiecloudKey: json['COOKIECLOUD_KEY'] as String?,
  cookiecloudPassword: json['COOKIECLOUD_PASSWORD'] as String?,
  cookiecloudInterval: _intFromJson(json['COOKIECLOUD_INTERVAL']),
  cookiecloudBlacklist: json['COOKIECLOUD_BLACKLIST'] as String?,
  transferThreads: _intFromJson(json['TRANSFER_THREADS']),
  movieRenameFormat: json['MOVIE_RENAME_FORMAT'] as String?,
  tvRenameFormat: json['TV_RENAME_FORMAT'] as String?,
  renameFormatS0Names: _stringListFromJson(json['RENAME_FORMAT_S0_NAMES']),
  defaultSub: json['DEFAULT_SUB'] as String?,
  scrapFollowTmdb: _boolFromJson(json['SCRAP_FOLLOW_TMDB']),
  mpServerHost: json['MP_SERVER_HOST'] as String?,
  wallpaper: json['WALLPAPER'] as String?,
  customizeWallpaperApiUrl: json['CUSTOMIZE_WALLPAPER_API_URL'] as String?,
  pluginMarket: json['PLUGIN_MARKET'] as String?,
  pluginStatisticShare: _boolFromJson(json['PLUGIN_STATISTIC_SHARE']),
  pluginAutoReload: _boolFromJson(json['PLUGIN_AUTO_RELOAD']),
  githubToken: json['GITHUB_TOKEN'] as String?,
  githubProxy: json['GITHUB_PROXY'] as String?,
  pipProxy: json['PIP_PROXY'] as String?,
  repoGithubToken: json['REPO_GITHUB_TOKEN'] as String?,
  bigMemoryMode: _boolFromJson(json['BIG_MEMORY_MODE']),
  encodingDetectionPerformanceMode: _boolFromJson(
    json['ENCODING_DETECTION_PERFORMANCE_MODE'],
  ),
  encodingDetectionMinConfidence: _doubleFromJson(
    json['ENCODING_DETECTION_MIN_CONFIDENCE'],
  ),
  memoryGcInterval: _intFromJson(json['MEMORY_GC_INTERVAL']),
  securityImageDomains: _stringListFromJson(json['SECURITY_IMAGE_DOMAINS']),
  securityImageSuffixes: _stringListFromJson(json['SECURITY_IMAGE_SUFFIXES']),
  passkeyRequireUv: _boolFromJson(json['PASSKEY_REQUIRE_UV']),
  passkeyAllowRegisterWithoutOtp: _boolFromJson(
    json['PASSKEY_ALLOW_REGISTER_WITHOUT_OTP'],
  ),
  workflowStatisticShare: _boolFromJson(json['WORKFLOW_STATISTIC_SHARE']),
  rcloneSnapshotCheckFolderModtime: _boolFromJson(
    json['RCLONE_SNAPSHOT_CHECK_FOLDER_MODTIME'],
  ),
  openlistSnapshotCheckFolderModtime: _boolFromJson(
    json['OPENLIST_SNAPSHOT_CHECK_FOLDER_MODTIME'],
  ),
  dockerClientApi: json['DOCKER_CLIENT_API'] as String?,
  playwrightBrowserType: json['PLAYWRIGHT_BROWSER_TYPE'] as String?,
  aiAgentEnable: _boolFromJson(json['AI_AGENT_ENABLE']),
  aiAgentGlobal: _boolFromJson(json['AI_AGENT_GLOBAL']),
  llmProvider: json['LLM_PROVIDER'] as String?,
  llmModel: json['LLM_MODEL'] as String?,
  llmApiKey: json['LLM_API_KEY'] as String?,
  llmBaseUrl: json['LLM_BASE_URL'] as String?,
  llmMaxContextTokens: _intFromJson(json['LLM_MAX_CONTEXT_TOKENS']),
  llmTemperature: _doubleFromJson(json['LLM_TEMPERATURE']),
  llmMaxIterations: _intFromJson(json['LLM_MAX_ITERATIONS']),
  llmToolTimeout: _intFromJson(json['LLM_TOOL_TIMEOUT']),
  llmVerbose: _boolFromJson(json['LLM_VERBOSE']),
  llmMaxMemoryMessages: _intFromJson(json['LLM_MAX_MEMORY_MESSAGES']),
  llmMemoryRetentionDays: _intFromJson(json['LLM_MEMORY_RETENTION_DAYS']),
  llmRedisMemoryRetentionDays: _intFromJson(
    json['LLM_REDIS_MEMORY_RETENTION_DAYS'],
  ),
  aiRecommendEnabled: _boolFromJson(json['AI_RECOMMEND_ENABLED']),
  aiRecommendUserPreference: json['AI_RECOMMEND_USER_PREFERENCE'] as String?,
  tavilyApiKey: json['TAVILY_API_KEY'] as String?,
  aiRecommendMaxItems: _intFromJson(json['AI_RECOMMEND_MAX_ITEMS']),
  version: json['VERSION'] as String?,
  authVersion: json['AUTH_VERSION'] as String?,
  indexerVersion: json['INDEXER_VERSION'] as String?,
  frontendVersion: json['FRONTEND_VERSION'] as String?,
);
