// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'subscribe_models.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$SubscribeItemImpl _$$SubscribeItemImplFromJson(Map<String, dynamic> json) =>
    _$SubscribeItemImpl(
      id: _intFromJson(json['id']),
      name: json['name'] as String?,
      year: json['year'] as String?,
      type: json['type'] as String?,
      keyword: json['keyword'] as String?,
      tmdbid: _intFromJson(json['tmdbid']),
      doubanid: _intFromJson(json['doubanid']),
      bangumiid: _intFromJson(json['bangumiid']),
      mediaid: json['mediaid'] as String?,
      season: _intFromJson(json['season']),
      poster: json['poster'] as String?,
      backdrop: json['backdrop'] as String?,
      vote: _doubleFromJson(json['vote']),
      description: json['description'] as String?,
      filter: json['filter'] as String?,
      include: json['include'] as String?,
      exclude: json['exclude'] as String?,
      quality: json['quality'] as String?,
      resolution: json['resolution'] as String?,
      effect: json['effect'] as String?,
      totalEpisode: _intFromJson(json['total_episode']),
      startEpisode: _intFromJson(json['start_episode']),
      lackEpisode: _intFromJson(json['lack_episode']),
      note: _intListFromJson(json['note']),
      state: json['state'] as String?,
      lastUpdate: json['last_update'] as String?,
      username: json['username'] as String?,
      sites: _intListFromJson(json['sites']),
      downloader: json['downloader'] as String?,
      bestVersion: _intFromJson(json['best_version']),
      currentPriority: (json['current_priority'] as num?)?.toInt(),
      savePath: json['save_path'] as String?,
      searchImdbid: _intFromJson(json['search_imdbid']),
      date: json['date'] as String?,
      customWords: json['custom_words'] as String?,
      mediaCategory: json['media_category'] as String?,
      filterGroups: json['filter_groups'],
      episodeGroup: json['episode_group'],
      count: _intFromJson(json['count']),
    );

Map<String, dynamic> _$$SubscribeItemImplToJson(_$SubscribeItemImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'year': instance.year,
      'type': instance.type,
      'keyword': instance.keyword,
      'tmdbid': instance.tmdbid,
      'doubanid': instance.doubanid,
      'bangumiid': instance.bangumiid,
      'mediaid': instance.mediaid,
      'season': instance.season,
      'poster': instance.poster,
      'backdrop': instance.backdrop,
      'vote': instance.vote,
      'description': instance.description,
      'filter': instance.filter,
      'include': instance.include,
      'exclude': instance.exclude,
      'quality': instance.quality,
      'resolution': instance.resolution,
      'effect': instance.effect,
      'total_episode': instance.totalEpisode,
      'start_episode': instance.startEpisode,
      'lack_episode': instance.lackEpisode,
      'note': _intListToJson(instance.note),
      'state': instance.state,
      'last_update': instance.lastUpdate,
      'username': instance.username,
      'sites': _intListToJson(instance.sites),
      'downloader': instance.downloader,
      'best_version': instance.bestVersion,
      'current_priority': instance.currentPriority,
      'save_path': instance.savePath,
      'search_imdbid': instance.searchImdbid,
      'date': instance.date,
      'custom_words': instance.customWords,
      'media_category': instance.mediaCategory,
      'filter_groups': instance.filterGroups,
      'episode_group': instance.episodeGroup,
      'count': instance.count,
    };

_$SubscribeShareItemImpl _$$SubscribeShareItemImplFromJson(
  Map<String, dynamic> json,
) => _$SubscribeShareItemImpl(
  id: _intFromJson(json['id']),
  name: json['name'] as String?,
  year: json['year'] as String?,
  type: json['type'] as String?,
  keyword: json['keyword'] as String?,
  tmdbid: _intFromJson(json['tmdbid']),
  poster: json['poster'] as String?,
  backdrop: json['backdrop'] as String?,
  vote: _doubleFromJson(json['vote']),
  description: json['description'] as String?,
  season: _intFromJson(json['season']),
  totalEpisode: _intFromJson(json['total_episode']),
  shareUser: json['share_user'] as String?,
  shareTime: json['share_time'] as String?,
);

Map<String, dynamic> _$$SubscribeShareItemImplToJson(
  _$SubscribeShareItemImpl instance,
) => <String, dynamic>{
  'id': instance.id,
  'name': instance.name,
  'year': instance.year,
  'type': instance.type,
  'keyword': instance.keyword,
  'tmdbid': instance.tmdbid,
  'poster': instance.poster,
  'backdrop': instance.backdrop,
  'vote': instance.vote,
  'description': instance.description,
  'season': instance.season,
  'total_episode': instance.totalEpisode,
  'share_user': instance.shareUser,
  'share_time': instance.shareTime,
};
