// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'recommend_api_item.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$RecommendApiItemImpl _$$RecommendApiItemImplFromJson(
  Map<String, dynamic> json,
) => _$RecommendApiItemImpl(
  source: json['source'] as String?,
  type: json['type'] as String?,
  title: json['title'] as String?,
  en_title: json['en_title'] as String?,
  year: json['year'] as String?,
  title_year: json['title_year'] as String?,
  season: _asInt(json['season']),
  tmdb_id: _asString(json['tmdb_id']),
  imdb_id: _asString(json['imdb_id']),
  tvdb_id: _asString(json['tvdb_id']),
  douban_id: _asString(json['douban_id']),
  bangumi_id: _asString(json['bangumi_id']),
  collection_id: _asString(json['collection_id']),
  mediaid_prefix: _asString(json['mediaid_prefix']),
  media_id: _asString(json['media_id']),
  original_language: json['original_language'] as String?,
  original_title: json['original_title'] as String?,
  release_date: json['release_date'] as String?,
  backdrop_path: json['backdrop_path'] as String?,
  poster_path: json['poster_path'] as String?,
  vote_average: _asDouble(json['vote_average']),
  overview: json['overview'] as String?,
  category: json['category'] as String?,
  seasons: _asMap(json['seasons']),
  season_info: json['season_info'] as List<dynamic>? ?? const <dynamic>[],
  names: json['names'] as List<dynamic>? ?? const <dynamic>[],
  actors: json['actors'] as List<dynamic>? ?? const <dynamic>[],
  directors: json['directors'] as List<dynamic>? ?? const <dynamic>[],
  detail_link: json['detail_link'] as String?,
  adult: json['adult'] as bool?,
  created_by: json['created_by'] as List<dynamic>? ?? const <dynamic>[],
  episode_run_time:
      json['episode_run_time'] as List<dynamic>? ?? const <dynamic>[],
  genres: json['genres'] as List<dynamic>? ?? const <dynamic>[],
  first_air_date: json['first_air_date'] as String?,
  homepage: json['homepage'] as String?,
  languages: json['languages'] as List<dynamic>? ?? const <dynamic>[],
  last_air_date: json['last_air_date'] as String?,
  networks: json['networks'] as List<dynamic>? ?? const <dynamic>[],
  number_of_episodes: _asInt(json['number_of_episodes']),
  number_of_seasons: _asInt(json['number_of_seasons']),
  origin_country: json['origin_country'] as List<dynamic>? ?? const <dynamic>[],
  original_name: json['original_name'] as String?,
  production_companies:
      json['production_companies'] as List<dynamic>? ?? const <dynamic>[],
  production_countries:
      json['production_countries'] as List<dynamic>? ?? const <dynamic>[],
  spoken_languages:
      json['spoken_languages'] as List<dynamic>? ?? const <dynamic>[],
  release_dates: json['release_dates'] as List<dynamic>? ?? const <dynamic>[],
  status: json['status'] as String?,
  tagline: json['tagline'] as String?,
  genre_ids: json['genre_ids'] as List<dynamic>? ?? const <dynamic>[],
  vote_count: _asInt(json['vote_count']),
  popularity: _asDouble(json['popularity']),
  runtime: _asInt(json['runtime']),
  next_episode_to_air: _asMap(json['next_episode_to_air']),
  episode_groups: json['episode_groups'] as List<dynamic>? ?? const <dynamic>[],
  episode_group: _asMapOrNull(json['episode_group']),
);

Map<String, dynamic> _$$RecommendApiItemImplToJson(
  _$RecommendApiItemImpl instance,
) => <String, dynamic>{
  'source': instance.source,
  'type': instance.type,
  'title': instance.title,
  'en_title': instance.en_title,
  'year': instance.year,
  'title_year': instance.title_year,
  'season': instance.season,
  'tmdb_id': instance.tmdb_id,
  'imdb_id': instance.imdb_id,
  'tvdb_id': instance.tvdb_id,
  'douban_id': instance.douban_id,
  'bangumi_id': instance.bangumi_id,
  'collection_id': instance.collection_id,
  'mediaid_prefix': instance.mediaid_prefix,
  'media_id': instance.media_id,
  'original_language': instance.original_language,
  'original_title': instance.original_title,
  'release_date': instance.release_date,
  'backdrop_path': instance.backdrop_path,
  'poster_path': instance.poster_path,
  'vote_average': instance.vote_average,
  'overview': instance.overview,
  'category': instance.category,
  'seasons': instance.seasons,
  'season_info': instance.season_info,
  'names': instance.names,
  'actors': instance.actors,
  'directors': instance.directors,
  'detail_link': instance.detail_link,
  'adult': instance.adult,
  'created_by': instance.created_by,
  'episode_run_time': instance.episode_run_time,
  'genres': instance.genres,
  'first_air_date': instance.first_air_date,
  'homepage': instance.homepage,
  'languages': instance.languages,
  'last_air_date': instance.last_air_date,
  'networks': instance.networks,
  'number_of_episodes': instance.number_of_episodes,
  'number_of_seasons': instance.number_of_seasons,
  'origin_country': instance.origin_country,
  'original_name': instance.original_name,
  'production_companies': instance.production_companies,
  'production_countries': instance.production_countries,
  'spoken_languages': instance.spoken_languages,
  'release_dates': instance.release_dates,
  'status': instance.status,
  'tagline': instance.tagline,
  'genre_ids': instance.genre_ids,
  'vote_count': instance.vote_count,
  'popularity': instance.popularity,
  'runtime': instance.runtime,
  'next_episode_to_air': instance.next_episode_to_air,
  'episode_groups': instance.episode_groups,
  'episode_group': instance.episode_group,
};
